beerrecenzionservice/forms/beer_form.py
from flask_wtf.file import FileRequired
from wtforms import Form, StringField, validators, SelectField, FileField
from wtforms.widgets import TextArea


class BeerForm(Form):
    name = StringField('Nazwa', [
        validators.DataRequired()
    ])
    category = SelectField('Rodzaj')
    description = StringField('Opis', [
        validators.DataRequired()
    ], widget=TextArea())
    photo = FileField('Zdjęcie')

beerrecenzionservice/forms/comment_form.py
from wtforms import Form, StringField, validators, DateTimeField
from wtforms.widgets import TextArea


class CommentForm(Form):
    content = StringField('Treść', [
        validators.DataRequired()
    ], widget=TextArea())
    date = DateTimeField('Date')

beerrecenzionservice/forms/login_form.py
from wtforms import Form, StringField, validators, PasswordField, BooleanField


class LoginForm(Form):
    username = StringField('Username', [
        validators.DataRequired()
    ])
    password = PasswordField('Password', [
        validators.DataRequired()
    ])
    remember_me = BooleanField('Remember me')

beerrecenzionservice/forms/registration_form.py
from wtforms import Form, StringField, validators, PasswordField, BooleanField


class RegistrationForm(Form):
    username = StringField('Username', [
        validators.DataRequired(),
        validators.Length(min=4, max=25)])
    email = StringField('Email Address', [
        validators.DataRequired(),
        validators.Email()])
    password = PasswordField('New Password', [
        validators.DataRequired(),
        validators.EqualTo('confirm', message="Passwords must match")
    ])
    confirm = PasswordField('Repeat Password')
    accept_tos = BooleanField('I accept the TOS', [validators.DataRequired()])

beerrecenzionservice/forms/search_form.py
from wtforms import Form, StringField, validators


class SearchForm(Form):
    search_text = StringField('Podaj frazę', [
        validators.DataRequired()
    ])

beerrecenzionservice/views/beers_view.py
import os
from datetime import datetime

from flask import (Blueprint, flash, g, redirect, render_template, request, sessions, url_for)
from flask_login import current_user
from flask_uploads import UploadSet, IMAGES

from werkzeug.exceptions import abort

from beerrecenzionservice.firebase import firebase
from beerrecenzionservice.forms.beer_form import BeerForm
from beerrecenzionservice.forms.comment_form import CommentForm

from beerrecenzionservice.models.beer_model import Comment, Beer
from beerrecenzionservice.models.beercategory_model import BeerCategory

blueprint = Blueprint('beers', __name__, url_prefix='/beer')
photos = UploadSet('photos', IMAGES)


@blueprint.route('/<beer_id>', methods=('GET', 'POST'))
def beer(beer_id):
    form = CommentForm(request.form)
    selected_beer = None
    try:
        selected_beer = Beer.objects(id=beer_id).first()
    except:
        abort(404)

    if request.method == 'POST' and form.validate():
        if not current_user.is_authenticated:
            abort(401)

        user = current_user.user
        comment = Comment(content=form.content.data,
                          date=datetime.now().isoformat(' ', 'seconds'),
                          user=user)
        if selected_beer is not None:
            selected_beer.comments.append(comment)
            selected_beer.save()

        flash('Thanks for added comment')

    return render_template('beer.html', form=form, beer=selected_beer)


@blueprint.route('/search/<search_text>', methods=('GET', 'POST'))
def search_beers(search_text):
    beers = None
    try:
        beers = Beer.objects(name__icontains=search_text)
    except:
        abort(404)

    return render_template('category.html', beers=beers, category_name="Wyniki wyszukiwania: ", searching=True)


@blueprint.route('/add', methods=('GET', 'POST'))
def add_beer():
    form = BeerForm(request.form)
    categories = None
    try:
        categories = BeerCategory.objects()
    except:
        abort(404)

    form.category.choices = categories

    if request.method == 'POST' and form.validate():
        if not current_user.is_authenticated:
            abort(401)

        category_name = form.category.data
        category = BeerCategory.objects(name=category_name).first()
        user = current_user.user
        photo_file = request.files[form.photo.name]
        uploaded = None
        if len(photo_file.filename) > 0:
            storage = firebase.storage()
            filename, extension = os.path.splitext(photo_file.filename)
            uploaded = storage.child(f"images/{filename}-{datetime.timestamp(datetime.now())}{extension}").put(photo_file)

        beer = Beer(name=form.name.data,
                    category=category,
                    description=form.description.data,
                    user=user,
                    photo=uploaded)
        beer.save()
        flash('Thanks for added beer')
        return redirect(url_for('beers.beer', beer_id=beer.id))

    return render_template('add_beer.html', form=form)

beerrecenzionservice/views/categories_view.py
from flask import Blueprint, render_template
from werkzeug.exceptions import abort

from beerrecenzionservice.models.beer_model import Beer
from beerrecenzionservice.models.beercategory_model import BeerCategory

blueprint = Blueprint('categories', __name__, url_prefix='/categories')

@blueprint.route('/', methods=('GET', 'POST'))
def categories():
    categories = BeerCategory.objects()
    return render_template('categories.html', categories=categories)


@blueprint.route('/<category_id>', methods=('GET', 'POST'))
def beers(category_id):
    beers = None
    try:
        category = BeerCategory.objects(id=category_id).first()
        beers = Beer.objects(category=category)
    except:
        abort(404)

    return render_template('category.html', beers=beers, category_name=category.name)

beerrecenzionservice/views/userauth_view.py
from flask import (Blueprint, flash, g, redirect, render_template, request, sessions, url_for)

from flask_login import login_user, logout_user

from werkzeug.security import check_password_hash, generate_password_hash

from beerrecenzionservice.forms.registration_form import RegistrationForm
from beerrecenzionservice.forms.login_form import LoginForm
from beerrecenzionservice.models.user_model import User
from beerrecenzionservice.wrappers import UserWrapper

blueprint = Blueprint('auth', __name__, url_prefix='/auth')


@blueprint.route('/register', methods=('GET', 'POST'))
def register():
    form = RegistrationForm(request.form)

    if request.method == 'POST' and form.validate():
        username_exists = User.objects(username=form.username.data).first()

        if not username_exists:
            user = User(username=form.username.data,
                        email=form.email.data,
                        password=generate_password_hash(f'{form.username.data}:{form.password.data}'))
            user.save()
            flash('Thanks for registering')
            return redirect(url_for('auth.login'))
        else:
            form.username.errors.append("Użytkownik o takiej nazwie już istnieje.")
    return render_template('auth/register.html', form=form)


@blueprint.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm(request.form)

    if request.method == 'POST' and form.validate():
        user = User.objects(username=form.username.data).first()
        if user and check_password_hash(user.password, f'{form.username.data}:{form.password.data}'):
            login_user(UserWrapper(user))
            return redirect(request.args.get("next") or url_for("main.index"))
        else:
            form.username.errors.append("Niepoprawne dane logowania.")

    return render_template('auth/login.html', form=form)

@blueprint.route('/logout', methods=('GET',))
def logout():
    logout_user()
    return redirect('login')

beerrecenzionservice/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

beerrecenzionservice/templates/add_beer.html
{% extends 'base.html' %}
{% block content %}
{% from "_formhelpers.html" import render_field %}
<div class="container">
<div class="login-form" style="margin-top:100px">
    <div class="form-group">
<form method="post" enctype="multipart/form-data">
    <h2 class="text-center">{% block title %}Dodawanie piwa{% endblock %}</h2>
  <div class="form-group">
    {{ render_field(form.name, class='form-control') }}
  </div>
    <div class="form-group">
    {{ render_field(form.description, class='form-control') }}
  </div>
  <div class="form-group">
    {{ render_field(form.category, class='form-control') }}
  </div>
      <div class="form-group">
    {{ render_field(form.photo, class='form-control') }}
  </div>
    <div class="form-group">
    <input type=submit class="btn btn-success btn-block" value=Dodaj piwo>
    </div>
  <p>
</form>
    </div>
    </div></div>
{% endblock %}

beerrecenzionservice/templates/base.html
{% extends "bootstrap/base.html" %}
<title>{% block title %}{% endblock %} - Flaskr</title>
{%block navbar%}
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
    <div class="navbar-header">
  <a class="navbar-brand" href="/">Beer Recenzion Service</a>
    </div>
        <ul class="nav navbar-nav">
      <li><a href="/">Home</a></li>
      <li><a href="/categories">Rodzaje piw</a></li>
            {% if current_user.is_authenticated and current_user.user.group %}
            <li><a href="/admin">Panel administracyjny</a></li>
            {% endif %}
    </ul>
    <ul class="nav navbar-nav navbar-right">
   {% if current_user.is_authenticated %}
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> {{ current_user.user.username }}</a></li>
      <li><a  href="{{ url_for('auth.logout') }}"><span class="glyphicon glyphicon-log-out"></span> Log Out</a></li>
    {% else %}
      <li><a href="{{ url_for('auth.register') }}">Register</a></li>
      <li><a href="{{ url_for('auth.login') }}"><span class="glyphicon glyphicon-log-in"></span> Log in</a></li>
    {% endif %}
  </ul>
  </div>
    </div>
</nav>
{% endblock %}
<div class="container">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</div>

beerrecenzionservice/templates/beer.html
{% extends 'base.html' %}
{% block content %}
{% from "_formhelpers.html" import render_field %}
<div class="container">
  <div style="display: flex; justify-content: space-between; margin-top:40px">
    <div>
  <h1>{% block title %}{{beer.name}}{% endblock %}</h1>
  <h3>{{beer.category.name}}</h3>
    </div>
                            {% if beer.photo %}
                        <img class="card-img-top" style="margin-top: 20px; max-height: 300px; max-width: 300px;"  src="{{beer.photo}}" alt="Card image cap2">
                    {% else %}
                        <img class="card-img-top" style="margin-top: 20px; max-height: 300px; max-width: 300px" src="{{url_for('static', filename='no_photo.png')}}" alt="Card image cap2">
                    {% endif %}
  </div>
    <h2 style="margin-top:20px; margin-bottom: 20px">Komentarze:</h2>
  {% for result in beer.comments %}
    <div><h4>{{result.content}}</h4><h5>{{result.date}} {{result.user}}</h5>
      <hr/>
  {%endfor%}
      {% if current_user.is_authenticated %}
  <form method=post>
    <h2 style="margin-bottom: 20px">Dodaj komentarz:</h2>
  <div class="form-group" style="max-width:600px">
    {{ render_field(form.content, class='form-control') }}
    <input type=submit class="btn btn-primary btn-block" style="margin-top: 20px" value=Dodaj>
  </div>
</form>
      {%endif%}
</div>
{% endblock %}

beerrecenzionservice/templates/beers.html
{% extends 'base.html' %}
{% block content %}
{% from "_formhelpers.html" import render_field %}
{% for result in beers %}
    <div class="card" style="float: left; width: 18rem;">
        <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-body">
    <h4 class="card-title">{{result.name}}</h4>
    <p class="card-text">{{result.category}}</p>
    <a href="" class="btn btn-primary">Zobacz więcej</a>
  </div>
</div>
    {% endfor %}

beerrecenzionservice/templates/categories.html
{% extends 'base.html' %}
{% block content %}
{% from "_formhelpers.html" import render_field %}
<div class="container" style="margin-top:40px">
    <h2>Rodzaje piw:</h2>
<div class="list-group">
  {% for result in categories %}
  <a href="/categories/{{result.id}}" class="list-group-item list-group-item-action">{{result.name}}</a>
    {% endfor %}
</div>
</div>
{% endblock %}

beerrecenzionservice/templates/category.html
{% extends 'base.html' %}
{% block content %}
{% from "_formhelpers.html" import render_field %}
{%block styles %}
{{super()}}
<link rel="stylesheet" href="{{ url_for('static', filename='4.css') }}">
{%endblock%}
<div class="container" style="margin-top: 50px">
    <div style="display: flex; justify-content: space-between">
    <h3>{% block title %}{{category_name}}{% endblock %}</h3>
    {% if current_user.is_authenticated and not searching%}
        <a href="{{ url_for ('beers.add_beer')}}" class="btn btn-success" style="margin-top: 10px; margin-bottom:10px">Dodaj nowe piwo</a>
    {%endif%}
    </div>
    <div class="container-flex" style="flex-wrap: wrap;">
{% for result in beers %}
    <div class="element">
                            {% if result.photo %}
                        <img class="card-img-top" style="display: block; max-height: 150px; max-width: 150px; margin-left: auto; margin-right: auto"  src="{{result.photo}}" alt="Card image cap2">
                    {% else %}
                        <img class="card-img-top" style="max-height: 150px; max-width: 150px" src="{{url_for('static', filename='no_photo.png')}}" alt="Card image cap2">
                    {% endif %}
  <div class="card-body">
    <h4 class="card-title">{{result.name}}</h4>
    <p class="card-text">{{result.category}}</p>
    <a href="{{ url_for ('beers.beer', beer_id=result.id)}}" class="btn btn-primary">Szczegóły</a>
  </div>
</div>
    {% endfor %}
    </div>
</div>

{% endblock %}

beerrecenzionservice/templates/index.html
{% extends 'base.html' %}
{% block content %}
{% from "_formhelpers.html" import render_field %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
<div class="container">
<div id="myCarousel" class="carousel slide" style="height:400px"  data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" style="height:400px" >
    <div class="item active" style="height:400px" >
      <img src="../static/piwo1.jpg" style="height: 100%; width: 100%; object-fit: cover" alt="Piwo1">
    </div>

    <div class="item" style="height:400px" >
      <img src="../static/piwo2.png" style="height: 100%; width: 100%; object-fit: cover" alt="Piwo2">
    </div>

    <div class="item" style="height:400px" >
      <img src="../static/piwo3.jpg" style="height: 100%; width: 100%; object-fit: cover" alt="Piwo3">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="jumbotron">
    <h1>Witaj na naszej stronie z recenzjami napojów piwnych.</h1>
    <p>Jest to strona poświęcona różnego rodzaju napojom piwnym.
        U nas dowiesz się jakie piwo posiada opinie oraz gdzie w okilicy możesz je
        kupić aby skosztować wybranego wspaniałego trunku.</p>
</div>
    <div style="display: flex; flex-wrap: wrap;">
        <div style="margin: 0px 10px 10px 10px">
          <h3>Wyszukiwanie:</h3>
          <form method=post>
              {{ render_field(form.search_text, class='form-control') }}
            <button type="submit" class="btn btn-success" style="margin-top: 10px">Szukaj piwa</button>
          </form>
        </div>
        <div style="margin: 0px 10px 10px 10px; flex: 1;">
            <h3>Ostatnio komentowane piwa:</h3>
            <div style="display: flex; flex-wrap: wrap; justify-content: flex-start;">
                {% for result in beers %}
                <div class="card" style="margin: 10px 20px 10px 0px; width: 150px">
                            {% if result.photo %}
                        <img class="card-img-top" style="display: block; max-height: 150px; max-width: 150px; margin-left: auto; margin-right: auto"  src="{{result.photo}}" alt="Card image cap2">
                    {% else %}
                        <img class="card-img-top" style="max-height: 150px; max-width: 150px" src="{{url_for('static', filename='no_photo.png')}}" alt="Card image cap2">
                    {% endif %}
                    <div class="card-body">
                        <h4 class="card-title">{{result.name}}</h4>
                        <p class="card-text">{{result.category}}</p>
                        <a href="{{ url_for ('beers.beer', beer_id=result.id)}}" class="btn btn-primary">Szczegóły</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}